name: Deploy lambda function
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate output.zip
      run: |
        npm install
        zip -r output.zip *
    - name: Upload output.zip
      uses: actions/upload-artifact@v2
      with:
        name: output.zip
        path: output.zip
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download output.zip
      uses: actions/download-artifact@v2
      with:
        name: output.zip
    - name: AWS Lambda Deploy
      if: github.ref == 'refs/heads/main'
      uses: appleboy/lambda-action@v0.1.9
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: example-lambda-branch-name
        zip_file: output.zip
        dry_run: true