name: Deploy lambda function
on: 
  push:
    branches:
      - main
jobs:

  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: AWS Lambda Deploy
      if: github.ref == 'refs/heads/main'
      uses: appleboy/lambda-action@v0.1.9
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: example-lambda-branch-name
        zip_file: example-lambda-branch-name.zip
        dry_run: true